name: Test Code (Style, Tests)

on: [ push, pull_request ]

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Gradle Test Core
        env:
          INTEGRATION_TEST: false
        # checkstyle would also run as part of the `check` task
        run: ./gradlew clean check jacocoTestReport -x checkstyleMain -x checkstyleTest